-------------------------------------------
/*
PROCEDURE 
*/
-------------------------------------------

USE NORTHWND

GO 

DROP PROCEDURE IF EXISTS DBO.INSERTCOSTUMER;

GO

CREATE PROCEDURE DBO.INSERTCOSTUMER
(
@COSTUMERID NVARCHAR (5)
,@COMPANYNAME NVARCHAR(40)
,@CONTACTNAME NVARCHAR (30) 
,@CONTACTTITLE NVARCHAR(30) 
,@ADDRESS NVARCHAR(60) 
,@CITY NVARCHAR(15) 
,@REGION NVARCHAR(15) 
,@POSTALCODE NVARCHAR(10) 
,@COUNTRY NVARCHAR (24) 
,@PHONE NVARCHAR (24) 
,@FAX NVARCHAR (24) 
)
AS
BEGIN;


DECLARE @CUSTOMER_ID NVARCHAR(5);
SET NOCOUNT ON

INSERT INTO [DBO].[CUSTOMERS] (
[CUSTOMERID]
,[COMPANYNAME]
,[CONTACTNAME]
,[CONTACTTITLE]
,[ADDRESS]
,[CITY]
,[REGION]
,[POSTALCODE]
,[COUNTRY]
,[PHONE]
,[FAX]
)
VALUES 
(
@COSTUMERID
,@COMPANYNAME
,@CONTACTNAME
,@CONTACTTITLE
,@ADDRESS
,@CITY
,@REGION
,@POSTALCODE
,@COUNTRY
,@PHONE
,@FAX)

SELECT [CUSTOMER_ID] = SCOPE_IDENTITY();
SELECT 
[CUSTOMERID]
,[COMPANYNAME]
,[CONTACTNAME]
,[CONTACTTITLE]
,[ADDRESS]
,[CITY]
,[REGION]
,[POSTALCODE]
,[COUNTRY]
,[PHONE]
,[FAX]
,[CUSTOMER_ID]
FROM 
[DBO].[CUSTOMERS] 
WHERE CUSTOMER_ID = @CUSTOMER_ID;

SET NOCOUNT OFF

END;

-------------------------------------------
/*
DECLARE VARIABLES
*/
-------------------------------------------


--DECLARE @CUSTOMERID NVARCHAR;
EXEC DBO.INSERTCOSTUMER
@COSTUMERID = 'FFGF'
,@COMPANYNAME = 'TESTE TESTE'
,@CONTACTNAME = 'THOMAS HARDY'
,@CONTACTTITLE = 'OWNER'
,@ADDRESS = 'CERRITO 333'
,@CITY  = 'LONDON'
,@REGION  = 'LONDON'
,@POSTALCODE = '05432-043'
,@COUNTRY  = 'UK' 
,@PHONE = '(604) 555-4729'
,@FAX = '(604) 555-3745'

--SELECT * FROM [DBO].[CUSTOMERS]
--WHERE CUSTOMERID = 'FFGF'
