--SELECT PADRÃO, IMPORTANTE SABER QUAIS CAMPOS SÃO NECESSÁRIOS ISSO EVITA USO DESNECESSÁRIO DE MEMÓRIA DA BASE
SELECT 
SALESORDERDETAILID, 
LINETOTAL
FROM SALES.SALESORDERDETAIL

--EXEMPLO DE AGRUPAMENTO
SELECT 
SALESORDERID, 
SUM (LINETOTAL) AS TOTAL
FROM SALES.SALESORDERDETAIL
GROUP BY SALESORDERID

--AGRUPAMENTO REFINANDO A PESQUISA COM HAVING, CASO PRECISE LIMITAR MAIS OS DADOS
SELECT 
SALESORDERID,
SUM(LINETOTAL) AS TOTAL
FROM SALES.SALESORDERDETAIL
GROUP BY SALESORDERID
HAVING SUM(LINETOTAL) < 10
ORDER BY SALESORDERID

--EXEMPLO DE EXCEPT, RETORNA OS CAMPOS DA TABELA A NÃO ESTÃO NA TABELA B
SELECT BUSINESSENTITYID
FROM HUMANRESOURCES.EMPLOYEE
EXCEPT
SELECT BUSINESSENTITYID
FROM HUMANRESOURCES.JOBCANDIDATE

SELECT BUSINESSENTITYID
FROM HUMANRESOURCES.JOBCANDIDATE
EXCEPT
SELECT BUSINESSENTITYID
FROM HUMANRESOURCES.EMPLOYEE

--EXIBI APENAS OS CAMPOS EM COMUM
SELECT BUSINESSENTITYID
FROM HUMANRESOURCES.EMPLOYEE
INTERSECT
SELECT BUSINESSENTITYID
FROM HUMANRESOURCES.JOBCANDIDATE

--UNI OS CAMPOS EM COMUM
SELECT *
FROM HUMANRESOURCES.EMPLOYEE
UNION
SELECT *
FROM HUMANRESOURCES.EMPLOYEE

--UNI TODOS OS CAMPOS
SELECT *
FROM HUMANRESOURCES.EMPLOYEE
UNION ALL
SELECT *
FROM HUMANRESOURCES.EMPLOYEE
