USE AdventureWorks2019 -- BASE DISPONIVEL PARA DOWNLOAD MS

 -- EXECUTOU EM 9 SEG

CREATE TABLE BIGINT_TESTE(
[BIG][BIGINT] NULL
) ON [PRIMARY]

GO -- EXECUCAO SEQUENCIAL

CREATE TABLE TINYINT_TESTE(
[TYNY][TINYINT]NULL
)ON [PRIMARY]
GO

INSERT INTO BIGINT_TESTE([BIG])
VALUES ('255')

GO 10000

INSERT INTO TINYINT_TESTE ([TYNY])
VALUES ('255')
GO 10000

SP_SPACEUSED N'DBO.BIGINT_TESTE' 
GO
SP_SPACEUSED N'DBO.TINYINT_TESTE'
GO

--DROP TABLE TINYINT_TESTE